import { NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { z } from 'zod';

const RequestSchema = z.object({
  orderId: z.string().uuid('ID order tidak valid.'),
  paymentMethod: z.enum(['BANK_TRANSFER', 'CASH', 'QRIS', 'OTHER']),
  proofPath: z.string().min(1, 'Path bukti transfer wajib diisi.'),
  proofFileName: z.string().min(1, 'Nama file bukti transfer wajib diisi.'),
  proofMimeType: z.string().min(1, 'Tipe mime bukti transfer wajib diisi.'),
  proofSizeBytes: z.number().int().positive('Ukuran file bukti transfer tidak valid.'),
});

export async function POST(req: Request) {
  const supabase = createAdminClient();

  try {
    const body = await req.json();
    const validation = RequestSchema.safeParse(body);

    if (!validation.success) {
      const firstError = validation.error.issues[0]?.message || 'Data tidak valid.';
      return NextResponse.json({
        success: false,
        message: firstError,
        errors: validation.error.flatten().fieldErrors
      }, { status: 400 });
    }

    const { orderId, paymentMethod, proofPath, proofFileName, proofMimeType, proofSizeBytes } = validation.data;

    // 1. Validate order exists and fetch status/amount
    const { data: order, error: orderError } = await supabase
      .from('orders')
      .select('id, status, total_amount')
      .eq('id', orderId)
      .single();

    if (orderError || !order) {
      return NextResponse.json({
        success: false,
        message: 'Order tidak ditemukan atau tidak valid.'
      }, { status: 404 });
    }

    // 2. Validate order status eligibility
    if (!['PENDING_PAYMENT', 'WAITING_VERIFICATION', 'REJECTED'].includes(order.status)) {
      return NextResponse.json({
        success: false,
        message: `Order dengan status ${order.status} tidak dapat menerima bukti pembayaran.`
      }, { status: 400 });
    }

    // 3. For FREE ticket types, total_amount <= 0.
    if (order.total_amount <= 0) {
      return NextResponse.json({
        success: false,
        message: 'Order tiket gratis tidak memerlukan bukti pembayaran.'
      }, { status: 400 });
    }

    // 4. Verify file path ownership and format matching order details to prevent fraud uploads
    // The proof path must start with event_id/order_id (generated by upload-url endpoint)
    // We check if the path contains the orderId.
    if (!proofPath.includes(orderId)) {
      return NextResponse.json({
        success: false,
        message: 'Akses tidak sah untuk file bukti pembayaran ini.'
      }, { status: 403 });
    }

    // 5. Atomic submission using database transaction / rollback behavior.
    // We update the order status to WAITING_VERIFICATION and insert/update the payments record.
    // If the order already has payments records, we set their status to REJECTED or leave them,
    // and insert the new payment record to preserve history for auditing (resubmission support).
    
    // First, let's start a transactional process. Since Next.js uses client sdk,
    // we can use a pgSQL function OR run multiple queries. Let's do it using RPC to ensure atomicity.
    const { data: submitResult, error: submitError } = await supabase.rpc('submit_payment_proof_rpc', {
      p_order_id: orderId,
      p_payment_method: paymentMethod,
      p_amount: order.total_amount,
      p_proof_path: proofPath,
      p_proof_file_name: proofFileName,
      p_proof_mime_type: proofMimeType,
      p_proof_size_bytes: proofSizeBytes
    });

    if (submitError) {
      console.error('Submit Payment RPC Error:', submitError);
      return NextResponse.json({
        success: false,
        message: submitError.message.includes('VALIDATION_ERROR') ? submitError.message.split('VALIDATION_ERROR:')[1]?.trim() : 'Gagal memproses bukti pembayaran.'
      }, { status: 400 });
    }

    return NextResponse.json({
      success: true,
      message: 'Bukti pembayaran berhasil dikirim!',
      paymentId: submitResult.paymentId
    }, { status: 200 });

  } catch (error: any) {
    console.error('Submit Payment API Error:', error);
    return NextResponse.json({
      success: false,
      message: 'Terjadi kesalahan internal server.'
    }, { status: 500 });
  }
}
