import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { PDFDocument } from 'pdf-lib'
import { createClient } from '@supabase/supabase-js'
const envText = fs.readFileSync(path.resolve(process.cwd(), '.env.local'), 'utf8').replace(/^\uFEFF/, '')
for (const rawLine of envText.split(/\r?\n/)) { const line = rawLine.trimEnd(); const match = line.match(/^([A-Z0-9_]+)=(.*)$/); if (!match || process.env[match[1]]) continue; let value = match[2]; if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1); process.env[match[1]] = value }
const base = process.env.PHASE13_BASE_URL ?? 'http://localhost:3000'; const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const secret = process.env.SUPABASE_SECRET_KEY; assert(url && secret); const publishable = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ?? secret; const db = createClient(url, secret, { auth: { persistSession: false } })
async function session(emailKey, passwordKey) { const client = createClient(url, publishable, { auth: { persistSession: false } }); const { data, error } = await client.auth.signInWithPassword({ email: process.env[emailKey]?.trim(), password: process.env[passwordKey] }); assert(!error && data.session, `${emailKey} login failed`); const { createServerClient } = await import('@supabase/ssr'); const jar = new Map(); const ssr = createServerClient(url, publishable, { cookies: { getAll: () => [...jar].map(([name, value]) => ({ name, value })), setAll: (cookies) => cookies.forEach(({ name, value }) => jar.set(name, value)) } }); const result = await ssr.auth.setSession(data.session); assert(!result.error); return [...jar].map(([name, value]) => `${name}=${encodeURIComponent(value)}`).join('; ') }
async function request(pathname, cookies) { const response = await fetch(base + pathname, { headers: cookies ? { cookie: cookies } : {} }); const contentType = response.headers.get('content-type') ?? ''; return { response, bytes: contentType.includes('pdf') ? Buffer.from(await response.arrayBuffer()) : null, body: contentType.includes('json') ? await response.json() : null } }
function expectStatus(result, expected, label) { assert.equal(result.response.status, expected, `${label}: ${result.response.status} ${JSON.stringify(result.body)}`) }
expectStatus(await request('/api/admin/tickets/00000000-0000-0000-0000-000000000000/download'), 401, 'anonymous individual'); expectStatus(await request('/api/admin/orders/00000000-0000-0000-0000-000000000000/download-tickets'), 401, 'anonymous batch')
const nonAdmin = await session('PHASE13_NONADMIN_EMAIL', 'PHASE13_NONADMIN_PASSWORD'); const admin = await session('PHASE13_ADMIN_EMAIL', 'PHASE13_ADMIN_PASSWORD'); const superAdmin = await session('PHASE13_SUPER_ADMIN_EMAIL', 'PHASE13_SUPER_ADMIN_PASSWORD'); expectStatus(await request('/api/admin/tickets/00000000-0000-0000-0000-000000000000/download', nonAdmin), 403, 'non-admin individual'); expectStatus(await request('/api/admin/orders/00000000-0000-0000-0000-000000000000/download-tickets', nonAdmin), 403, 'non-admin batch')
const { data: tickets, error: ticketError } = await db.from('issued_tickets').select('id, order_id, ticket_code, qr_token, status, updated_at').order('created_at', { ascending: true }); assert(!ticketError && tickets?.length, 'No issued tickets available'); const downloadable = tickets.find((ticket) => ticket.status === 'ACTIVE' || ticket.status === 'CHECKED_IN'); assert(downloadable); const cancelled = tickets.find((ticket) => ticket.status === 'CANCELLED'); const before = JSON.stringify(downloadable)
for (const [label, cookies] of [['admin', admin], ['super-admin', superAdmin]]) { const individual = await request(`/api/admin/tickets/${downloadable.id}/download`, cookies); expectStatus(individual, 200, `${label} individual`); assert(individual.bytes?.subarray(0, 5).toString() === '%PDF-'); const pdf = await PDFDocument.load(individual.bytes); assert.equal(pdf.getPageCount(), 1); assert.equal(individual.response.headers.get('cache-control'), 'private, no-store, max-age=0') }
const batch = await request(`/api/admin/orders/${downloadable.order_id}/download-tickets`, admin); expectStatus(batch, 200, 'admin batch'); assert(batch.bytes?.subarray(0, 5).toString() === '%PDF-'); const batchPdf = await PDFDocument.load(batch.bytes); const expectedCount = tickets.filter((ticket) => ticket.order_id === downloadable.order_id && (ticket.status === 'ACTIVE' || ticket.status === 'CHECKED_IN')).length; assert.equal(batchPdf.getPageCount(), expectedCount)
if (cancelled) expectStatus(await request(`/api/admin/tickets/${cancelled.id}/download`, admin), 404, 'cancelled individual'); expectStatus(await request('/api/admin/tickets/not-a-uuid/download', admin), 400, 'invalid ticket UUID'); expectStatus(await request('/api/admin/orders/not-a-uuid/download-tickets', admin), 400, 'invalid order UUID'); const { data: after } = await db.from('issued_tickets').select('id, order_id, ticket_code, qr_token, status, updated_at').eq('id', downloadable.id).single(); assert.equal(JSON.stringify(after), before); console.log('Phase 14 acceptance checks passed')
